wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1667315906.519916
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 45
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.13.4
      8:
      - 1
      - 5
data.batch_size:
  desc: null
  value: 128
data.cache:
  desc: null
  value: false
data.channels:
  desc: null
  value: 1
data.dataset:
  desc: null
  value: fashion_mnist
data.image_size:
  desc: null
  value: 28
ddpm.beta_schedule:
  desc: null
  value: linear
ddpm.p2_loss_weight_gamma:
  desc: null
  value: 0.0
ddpm.p2_loss_weight_k:
  desc: null
  value: 1
ddpm.pred_x0:
  desc: null
  value: false
ddpm.self_condition:
  desc: null
  value: false
ddpm.timesteps:
  desc: null
  value: 1000
ema.beta:
  desc: null
  value: 0.995
ema.inv_gamma:
  desc: null
  value: 1.0
ema.min_value:
  desc: null
  value: 0.0
ema.power:
  desc: null
  value: 0.6666666666666666
ema.update_after_step:
  desc: null
  value: 100
ema.update_every:
  desc: null
  value: 10
model.dim:
  desc: null
  value: 64
model.dim_mults:
  desc: null
  value:
  - 1
  - 2
  - 4
optim.beta1:
  desc: null
  value: 0.9
optim.beta2:
  desc: null
  value: 0.99
optim.eps:
  desc: null
  value: 1.0e-08
optim.lr:
  desc: null
  value: 0.001
optim.optimizer:
  desc: null
  value: Adam
seed:
  desc: null
  value: 42
training.half_precision:
  desc: null
  value: false
training.log_every_steps:
  desc: null
  value: 100
training.loss_type:
  desc: null
  value: l1
training.num_sample:
  desc: null
  value: 64
training.num_train_steps:
  desc: null
  value: 12000
training.save_and_sample_every:
  desc: null
  value: 1000
wandb.entity:
  desc: null
  value: xmax1
wandb.job_type:
  desc: null
  value: training
wandb.log_model:
  desc: null
  value: true
wandb.log_sample:
  desc: null
  value: true
wandb.log_train:
  desc: null
  value: true
wandb.name:
  desc: null
  value: demo
wandb.project:
  desc: null
  value: jax-ddpm-demo
